version: 0.2

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - REPO_NAME=learn-with-nivas-react
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"react-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
